#!/usr/bin/env node
"use strict";
// Generated by the System2 compiler (Codex backend). Do not edit by hand.
// Stop / SubagentStop: report the change budget (ADAPTED — a report, not a
// block). Node stdlib ONLY. A report hook must never wedge the session, so
// on any error it exits 0 (fail-open is correct for a non-enforcement report).
let buf = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (c) => { if (buf.length < 1048576) buf += c; });
process.stdin.on("end", () => {
  try {
    process.stdout.write(JSON.stringify({
      systemMessage: "System2 budget (adapted, not enforced): report files touched and lines added/removed in your completion summary.",
    }));
  } catch (e) {}
  process.exit(0);
});
process.stdin.on("error", () => { process.exit(0); });
