#!/usr/bin/env node
"use strict";
// Generated by the System2 compiler. Do not edit by hand.
// Report the change budget; errors fail open because this hook does not enforce policy.
let buf = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (c) => { if (buf.length < 1048576) buf += c; });
process.stdin.on("end", () => {
  try {
    process.stdout.write(JSON.stringify({
      systemMessage: "System2 budget (advisory instruction only): report files touched and lines added/removed in your completion summary.",
    }));
  } catch (e) {}
  process.exit(0);
});
process.stdin.on("error", () => { process.exit(0); });
