// Generated by the System2 compiler. Do not edit by hand.
// The tool_call handler blocks unsafe operations before execution.

import type { ExtensionAPI, ExtensionContext, ToolCallEvent, BashToolCallEvent } from "@earendil-works/pi-coding-agent";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

// Dangerous-command matchers; order is semantic.
const DANGEROUS_REGEXES: [RegExp, string][] = [
  [new RegExp("\\brm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*|-r\\s+-f|-f\\s+-r|-[a-zA-Z]*r[a-zA-Z]*\\s+-[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*\\s+-[a-zA-Z]*r[a-zA-Z]*|--recursive\\s+--force|--force\\s+--recursive|--recursive\\s+-f|-f\\s+--recursive|-r\\s+--force|--force\\s+-r|--recursive[^|;&]*-f|-f[^|;&]*--recursive|-r[^|;&]*--force|--force[^|;&]*-r)\\s*(/|/\\*)\\s*($|;|\\||&)", "m"), "rm -rf targeting root filesystem (/) is extremely dangerous"],
  [new RegExp("\\brm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*|-r\\s+-f|-f\\s+-r|-[a-zA-Z]*r[a-zA-Z]*\\s+-[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*\\s+-[a-zA-Z]*r[a-zA-Z]*|--recursive\\s+--force|--force\\s+--recursive|--recursive\\s+-f|-f\\s+--recursive|-r\\s+--force|--force\\s+-r|--recursive[^|;&]*-f|-f[^|;&]*--recursive|-r[^|;&]*--force|--force[^|;&]*-r)\\s*\\./?(?:\\s|$|;|\\||&)", "m"), "rm -rf targeting current directory (.) could delete critical files"],
  [new RegExp("\\brm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*|-r\\s+-f|-f\\s+-r|-[a-zA-Z]*r[a-zA-Z]*\\s+-[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*\\s+-[a-zA-Z]*r[a-zA-Z]*|--recursive\\s+--force|--force\\s+--recursive|--recursive\\s+-f|-f\\s+--recursive|-r\\s+--force|--force\\s+-r|--recursive[^|;&]*-f|-f[^|;&]*--recursive|-r[^|;&]*--force|--force[^|;&]*-r)\\s*\\.\\./?(?:\\s|$|;|\\||&)", "m"), "rm -rf targeting parent directory (..) could delete critical files"],
  [new RegExp("\\brm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*)\\s*~", "m"), "rm -rf targeting the home directory (~) could delete user data"],
  [new RegExp("\\bsudo\\s+rm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*|-r\\s+-f|-f\\s+-r|-[a-zA-Z]*r[a-zA-Z]*\\s+-[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*\\s+-[a-zA-Z]*r[a-zA-Z]*|--recursive\\s+--force|--force\\s+--recursive|--recursive\\s+-f|-f\\s+--recursive|-r\\s+--force|--force\\s+-r|--recursive[^|;&]*-f|-f[^|;&]*--recursive|-r[^|;&]*--force|--force[^|;&]*-r)\\s+", "m"), "sudo rm -rf with elevated privileges is extremely dangerous"],
  [new RegExp("\\bchmod\\s+(.*\\s+)?777\\s+", "m"), "chmod 777 makes files world-writable and executable, a security risk"],
  [new RegExp("\\bgit\\s+reset\\s+--hard\\b", "m"), "git reset --hard discards uncommitted changes permanently"],
  [new RegExp("\\bgit\\s+push\\s+[^;|&]*--force(-with-lease)?[^;|&]*\\b(main|master)\\b", "m"), "git push --force to main/master can destroy shared commit history"],
  [new RegExp("\\bgit\\s+push\\s+[^;|&]*\\b(main|master)\\b[^;|&]*--force(-with-lease)?", "m"), "git push --force to main/master can destroy shared commit history"],
  [new RegExp("\\bgit\\s+push\\s+[^;|&]*-f\\s+[^;|&]*\\b(main|master)\\b", "m"), "git push -f to main/master can destroy shared commit history"],
  [new RegExp("\\bgit\\s+push\\s+[^;|&]*\\b(main|master)\\b[^;|&]*\\s+-f\\b", "m"), "git push -f to main/master can destroy shared commit history"],
  [new RegExp("\\bmkfs\\b", "m"), "mkfs reformats a filesystem and destroys all data on the device"],
  [new RegExp("\\bdd\\s+[^|;&]*\\bof=", "m"), "dd writing to a device/file (of=) can irreversibly overwrite data"],
  [new RegExp("\\bshutdown\\b", "m"), "shutdown halts the machine"],
  [new RegExp("\\b(curl|wget)\\b[^|]*\\|\\s*(sudo\\s+)?(sh|bash|zsh)\\b", "m"), "piping a downloaded script straight into a shell executes untrusted code"],
  [new RegExp("\\bDROP\\s+TABLE\\b", "i"), "DROP TABLE would permanently delete a database table and its data"],
  [new RegExp("\\bDELETE\\s+FROM\\s+\\w+\\s*($|;|\\|)", "im"), "DELETE FROM without a WHERE clause would delete all rows in the table"],
];

// Ported from sensitive-file-protector.py: segment/basename-anchored.
const SENSITIVE_REGEXES: [RegExp, string][] = [
  [new RegExp("(^|/)\\.env$", ""), "Environment file (.env)"],
  [new RegExp("(^|/)\\.env\\.[A-Za-z0-9_-]+$", ""), "Environment file (.env.*)"],
  [new RegExp("(^|/)\\.ssh(/|$)", ""), "SSH directory (.ssh/)"],
  [new RegExp("(^|/)\\.git(/|$)", ""), "Git directory (.git/)"],
  [new RegExp("(^|/)\\.aws(/|$)", ""), "AWS credentials directory (.aws/)"],
  [new RegExp("(^|/)\\.gnupg(/|$)", ""), "GPG directory (.gnupg/)"],
  [new RegExp("credentials", "i"), "File containing 'credentials'"],
  [new RegExp("secrets", "i"), "File containing 'secrets'"],
  [new RegExp("\\.pem$", "i"), "PEM certificate/key file (*.pem)"],
  [new RegExp("\\.key$", "i"), "Key file (*.key)"],
  [new RegExp("(^|/)id_rsa$", ""), "RSA private key (id_rsa)"],
  [new RegExp("(^|/)id_ed25519$", ""), "Ed25519 private key (id_ed25519)"],
  [new RegExp("(^|/)id_ecdsa$", ""), "ECDSA private key (id_ecdsa)"],
  [new RegExp("(^|/)\\.netrc$", ""), "Netrc credentials file (.netrc)"],
  [new RegExp("(^|/)\\.npmrc$", ""), "NPM config file (.npmrc) - may contain tokens"],
  [new RegExp("(^|/)\\.pypirc$", ""), "PyPI config file (.pypirc) - may contain tokens"],
];

// Per-role write scopes; absent or empty scopes deny writes.
const ROLE_WRITE_SCOPES: Map<string, string> = new Map([
  ["repo-governor", "^(CLAUDE\\.md|AGENTS\\.md|\\.claude/settings\\.json|spec/INDEX\\.md)$"],
  ["spec-coordinator", "^spec/context\\.md$"],
  ["requirements-engineer", "^spec/requirements\\.md$"],
  ["design-architect", "(?:^spec/design\\.md$)|(?:^spec/interfaces\\.json$)|(?:^spec/module-boundaries\\.json$)"],
  ["task-planner", "^spec/tasks\\.md$"],
  ["executor", "^(?!third_party/|vendor/|node_modules/|dist/|build/|out/|\\.git/).*(^spec/.*\\.md$|^docs/.*\\.md$|^README\\.md$|^CHANGELOG\\.md$|(^|/)(BUILD|WORKSPACE)(\\.bazel)?$|.*\\.(py|go|java|kt|kts|ts|tsx|js|jsx|rs|c|cc|cpp|h|hpp|cs|proto|sql|yaml|yml|json|toml|sh|bazel|bzl)$)"],
  ["test-engineer", "^(?!third_party/|vendor/|node_modules/|dist/|build/|out/|\\.git/).*(^spec/.*\\.md$|^docs/.*\\.md$|.*(/__tests__/|/tests?/).*\\.(py|go|java|kt|kts|ts|tsx|js|jsx|rs|c|cc|cpp|cs)$|.*(_test\\.go|\\.test\\.(ts|tsx|js|jsx)|\\.spec\\.(ts|tsx|js|jsx)|test_.*\\.py|.*_test\\.py)$|(^|/)(BUILD|WORKSPACE)(\\.bazel)?$|.*\\.(yaml|yml|json|toml)$)"],
  ["security-sentinel", "^spec/security\\.md$"],
  ["eval-engineer", "^(spec/evals\\.md|evals/.*\\.(md|py|yaml|yml|json|toml))$"],
  ["docs-release", "^(README\\.md|CHANGELOG\\.md|MIGRATIONS\\.md|docs/.*\\.md|spec/.*\\.md)$"],
  ["code-reviewer", ""],
  ["postmortem-scribe", "^postmortems/.*\\.md$"],
  ["mcp-toolsmith", "^(spec/mcp\\.md|mcp/.*\\.(md|py|ts|js|json|yaml|yml))$"],
]);

// Roles permitted to write when their path also matches the scope.
const WRITEABLE_ROLES: Set<string> = new Set(["code-reviewer", "design-architect", "docs-release", "eval-engineer", "executor", "mcp-toolsmith", "postmortem-scribe", "repo-governor", "requirements-engineer", "security-sentinel", "spec-coordinator", "task-planner", "test-engineer"]);

const VALID_ROLES: string[] = ["repo-governor", "spec-coordinator", "requirements-engineer", "design-architect", "task-planner", "executor", "test-engineer", "security-sentinel", "eval-engineer", "docs-release", "code-reviewer", "postmortem-scribe", "mcp-toolsmith"];
const READ_ONLY_DEFAULT_ROLE = "code-reviewer";
const ROLE_ENTRY_TYPE = "system2-role";
const HERE = path.dirname(fileURLToPath(import.meta.url));
const READ_ONLY_PROMPT = "System2 restrictive read-only fallback: no writes are authorized until /delegate selects a valid role.";
let activeRole: string = READ_ONLY_DEFAULT_ROLE;
let activeRolePrompt: string = READ_ONLY_PROMPT;

// Extract every supported path alias before applying policy.
const PATH_KEYS: string[] = [
  "path", "file_path", "filepath", "filename", "file", "target_file",
  "from", "to", "source", "destination", "old_path", "new_path",
];

function pathsOf(event: ToolCallEvent): string[] {
  const input = (event.input ?? {}) as Record<string, unknown>;
  const out: string[] = [];
  for (const key of PATH_KEYS) {
    const v = input[key];
    if (typeof v === "string" && v.length > 0) out.push(v);
  }
  return out;
}

function dangerousReason(command: string): string | undefined {
  for (const [re, reason] of DANGEROUS_REGEXES) {
    if (re.test(command)) return `block-dangerous: ${reason}`;
  }
  return undefined;
}

function sensitiveHit(text: string | undefined): string | undefined {
  if (!text) return undefined;
  for (const [re, description] of SENSITIVE_REGEXES) {
    if (re.test(text)) return description;
  }
  return undefined;
}

type ShellToken = { value: string; operator: boolean };
function shellTokens(command: unknown): ShellToken[] | null {
  if (typeof command !== "string" || command.length > 65536) return null;
  if (command.includes("`") || command.includes("$(")) return null;
  const out: ShellToken[] = [];
  let current = "";
  let quote = "";
  let escaped = false;
  const pushWord = () => {
    if (current) out.push({ value: current, operator: false });
    current = "";
  };
  for (let i = 0; i < command.length; i++) {
    const ch = command[i];
    if (escaped) { current += ch; escaped = false; continue; }
    if (ch === "\\" && quote !== "\'") { escaped = true; continue; }
    if (quote) {
      if (ch === quote) quote = ""; else current += ch;
      continue;
    }
    if (ch === "\'" || ch === '"') { quote = ch; continue; }
    if (/\s/.test(ch)) { pushWord(); continue; }
    if ("<>|;&".includes(ch)) {
      pushWord();
      let op = ch;
      if (i + 1 < command.length && (command[i + 1] === ch || (ch === "&" && command[i + 1] === ">"))) op += command[++i];
      out.push({ value: op, operator: true });
    } else current += ch;
    if (out.length > 256) return null;
  }
  if (escaped || quote) return null;
  pushWord();
  return out.length <= 256 ? out : null;
}

function shellWriteTargets(tokens: ShellToken[]): string[] | null {
  const targets: string[] = [];
  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (token.operator && /^(?:>|>>|&>)$/.test(token.value)) {
      const target = tokens[++i];
      if (!target || target.operator) return null;
      targets.push(target.value);
      continue;
    }
    const commandPosition = i === 0 || (tokens[i - 1].operator && /^(?:\||\|\||;|&&)$/.test(tokens[i - 1].value));
    if (commandPosition && !token.operator && /^(?:.*\/)?tee$/.test(token.value)) {
      let sawTarget = false;
      for (let j = i + 1; j < tokens.length && !tokens[j].operator; j++) {
        const value = tokens[j].value;
        if (!sawTarget && value.startsWith("-")) continue;
        sawTarget = true;
        targets.push(value);
      }
      if (!sawTarget) return null;
    }
  }
  return targets;
}

function loadRolePrompt(role: string): string | undefined {
  if (!VALID_ROLES.includes(role)) return undefined;
  const promptPath = path.resolve(HERE, "..", "prompts", `role-${role}.md`);
  try { return fs.readFileSync(promptPath, "utf8"); } catch { return undefined; }
}

function resetReadOnly(): void {
  activeRole = READ_ONLY_DEFAULT_ROLE;
  activeRolePrompt = loadRolePrompt(activeRole) ?? READ_ONLY_PROMPT;
}

function reconstructRole(ctx: ExtensionContext): void {
  resetReadOnly();
  const entries = ctx.sessionManager.getBranch().filter(
    (entry) => entry.type === "custom" && entry.customType === ROLE_ENTRY_TYPE,
  );
  if (entries.length === 0) return;
  const data = entries[entries.length - 1].data as { role?: unknown } | undefined;
  const role = data?.role;
  if (typeof role !== "string" || !VALID_ROLES.includes(role)) return;
  const prompt = loadRolePrompt(role);
  if (!prompt) return;
  activeRole = role;
  activeRolePrompt = prompt;
}

// Resolve project-relative targets, including existing symlink components.
function normalizeProjectPath(p: string, cwd: string): string | null {
  if (typeof p !== "string" || p.length === 0) return null;
  if (p === "~" || p.startsWith("~/") || path.isAbsolute(p)) return null;
  let root: string;
  try { root = fs.realpathSync(cwd); } catch { return null; }
  const parts = p.replace(/\\/g, "/").split("/");
  let current = root;
  for (let i = 0; i < parts.length; i++) {
    const part = parts[i];
    if (!part || part === ".") continue;
    if (part === "..") { current = path.dirname(current); } else { current = path.join(current, part); }
    try {
      const stat = fs.lstatSync(current);
      if (stat.isSymbolicLink()) {
        try { current = fs.realpathSync(current); } catch { return null; }
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") return null;
    }
    const rel = path.relative(root, current);
    if (rel === ".." || rel.startsWith(".." + path.sep) || path.isAbsolute(rel)) return null;
  }
  return path.relative(root, current).split(path.sep).join("/");
}

function offLeasePath(paths: string[], cwd: string): string | undefined {
  if (paths.length === 0) return undefined;
  const scope = ROLE_WRITE_SCOPES.get(activeRole);
  if (!WRITEABLE_ROLES.has(activeRole) || !scope) return paths[0];
  let re: RegExp;
  try {
    re = new RegExp("^(?:" + scope + ")");
  } catch {
    return paths[0];
  }
  for (const p of paths) {
    const norm = normalizeProjectPath(p, cwd);
    if (norm === null || !re.test(norm)) return p;
  }
  return undefined;
}

export default function (pi: ExtensionAPI) {
  resetReadOnly();
  pi.on("session_start", (_event, ctx) => reconstructRole(ctx));
  pi.on("session_tree", (_event, ctx) => reconstructRole(ctx));

  // Block the bounded, inspectable unsafe cases before execution.
  pi.on("tool_call", (event, ctx) => {
    if (event.toolName === "bash") {
      const command = (event as BashToolCallEvent).input?.command as unknown;
      if (typeof command !== "string") return { block: true, reason: "protect-sensitive: uninspectable bash command" };
      const reason = dangerousReason(command);
      if (reason) return { block: true, reason };
      const tokens = shellTokens(command);
      if (!tokens) return { block: true, reason: "protect-sensitive: shell token extraction failed or overflowed" };
      for (const token of tokens) {
        if (token.operator) continue;
        const hit = sensitiveHit(token.value);
        if (hit) return { block: true, reason: `protect-sensitive: ${hit}` };
      }
      const targets = shellWriteTargets(tokens);
      if (targets === null) return { block: true, reason: "enforce-lease: supported shell write target is uninspectable" };
      const off = offLeasePath(targets, ctx.cwd);
      if (off) return { block: true, reason: `enforce-lease: ${off} is outside the write scope for role ${activeRole}` };
      return;
    }
    const eventPaths = pathsOf(event);
    if (["read", "write", "edit"].includes(event.toolName) && eventPaths.length === 0) {
      return { block: true, reason: "protect-sensitive: uninspectable path input" };
    }
    for (const p of eventPaths) {
      const hit = sensitiveHit(p);
      if (hit) return { block: true, reason: `protect-sensitive: ${hit}` };
    }
    if (event.toolName === "write" || event.toolName === "edit") {
      const off = offLeasePath(eventPaths, ctx.cwd);
      if (off) return { block: true, reason: `enforce-lease: ${off} is outside the write scope for role ${activeRole}` };
    }
    return;
  });

  // Advisory only: this reminder computes no budget report.
  pi.on("agent_end", (_event, ctx) => {
    ctx.ui.notify(
      "System2 budget reminder: include files touched and lines added/removed in your completion summary.",
      "info",
    );
  });

  pi.on("before_agent_start", (event) => ({
    systemPrompt: `${event.systemPrompt}\n\nSystem2 orchestrator context is in .pi/SYSTEM.md.\n\n${activeRolePrompt}`,
  }));

  pi.registerCommand("delegate", {
    description: "Switch this session branch to one of the 13 System2 roles.",
    handler: async (args, ctx) => {
      const role = args.trim();
      if (!VALID_ROLES.includes(role)) {
        ctx.ui.notify(
          `Unknown role ${JSON.stringify(role)}. Valid roles: ${VALID_ROLES.join(", ")}.`,
          "error",
        );
        return;
      }
      const prompt = loadRolePrompt(role);
      if (!prompt) {
        ctx.ui.notify(`Role prompt for ${role} is unavailable; remaining read-only.`, "error");
        resetReadOnly();
        return;
      }
      pi.appendEntry(ROLE_ENTRY_TYPE, { role });
      activeRole = role;
      activeRolePrompt = prompt;
      ctx.ui.notify(`Delegated in-session to ${role}; its role contract applies on the next agent turn.`, "info");
    },
  });
}
