// Generated by the System2 compiler (build_pi_package.py). Do not edit by hand.
//
// Second Pi extension shipped in @deliberatecode/pi-system2. The gate itself lives in
// system2.ts; this extension registers a /system2-init command that materializes the
// project-level files System2 needs but which are NOT pi package component types
// (AGENTS.md, .pi/SYSTEM.md, the lock) from this package's payload/project/ directory
// into the current project.
//
// Security posture (design "Pi npm package" project-file-mismatch resolution; F5):
//   * The payload source is resolved PACKAGE-RELATIVE from this module's own location
//     (import.meta.url) -- robust across a global ~/.pi/agent/npm/ install and a
//     project-local .pi/npm/ install; no absolute path is baked into the package.
//   * Every managed target is constrained to WITHIN the project root (cwd): a managed
//     path that is absolute or escapes the root via ".." is REJECTED (fail closed),
//     never written.
//   * Idempotent: a target already byte-identical to the payload is skipped, so a
//     second run is a zero-diff no-op.
//   * Without --force a target that a user has modified is left UNTOUCHED (reported).
//   * With --force a user-modified target is overwritten, but the exact file being
//     replaced is PRINTED first.
//   * Unmanaged files are never touched -- only the paths in MANAGED_FILES are ever
//     considered.
//
// Node built-ins (node:fs / node:path / node:process / node:buffer / node:url) plus the
// pi-injected ExtensionAPI type only. NO npm dependency -- package.json declares none.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import * as fs from "node:fs";
import * as path from "node:path";
import * as process from "node:process";
import { Buffer } from "node:buffer";
import { fileURLToPath } from "node:url";

// The project-level files this package manages, relative to the project root. Each is
// materialized from payload/project/<relpath>. Embedded at build time as EXACTLY the
// set of files build_pi_package.py placed under payload/project/ (nothing else is ever
// touched).
const MANAGED_FILES: string[] = [".pi/SYSTEM.md", "AGENTS.md", "system2.pi.lock.json"];

// Package-relative anchor: this module lives in <packageRoot>/extensions/, so the
// payload directory is <packageRoot>/payload/project/. Resolved from the module's own
// path so it is correct wherever the package is installed.
const HERE = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(HERE, "..");
const PAYLOAD_ROOT = path.join(PACKAGE_ROOT, "payload", "project");

// Resolve a managed relpath to an absolute target strictly WITHIN projectRoot, or null
// if the path is absolute or resolves outside the root (fail closed).
function resolveWithinRoot(projectRoot: string, rel: string): string | null {
  if (path.isAbsolute(rel)) return null;
  const target = path.resolve(projectRoot, rel);
  const prefix = projectRoot.endsWith(path.sep) ? projectRoot : projectRoot + path.sep;
  if (target !== projectRoot && !target.startsWith(prefix)) return null;
  return target;
}

function readIfExists(p: string): Buffer | null {
  try {
    return fs.readFileSync(p);
  } catch {
    return null;
  }
}

export default function (pi: ExtensionAPI) {
  pi.registerCommand("/system2-init", {
    description:
      "Materialize System2 project files (AGENTS.md, .pi/SYSTEM.md, the lock) into this project from the package payload. Pass --force to overwrite user-modified files.",
    handler: async (args, ctx) => {
      const force = args.trim() === "--force";
      const projectRoot = process.cwd();
      const written: string[] = [];
      const skipped: string[] = [];
      const replaced: string[] = [];
      const rejected: string[] = [];

      for (const rel of MANAGED_FILES) {
        const target = resolveWithinRoot(projectRoot, rel);
        if (target === null) {
          // out-of-root / absolute managed path -> refuse to write it anywhere.
          rejected.push(rel);
          continue;
        }
        const payloadBytes = readIfExists(path.join(PAYLOAD_ROOT, rel));
        if (payloadBytes === null) {
          rejected.push(rel);
          continue;
        }
        const current = readIfExists(target);
        if (current !== null && current.equals(payloadBytes)) {
          // idempotent: already identical -> skip (second run is a zero-diff no-op).
          skipped.push(rel);
          continue;
        }
        if (current !== null && !force) {
          // user-modified (differs from payload) and no --force -> leave untouched.
          skipped.push(rel);
          ctx.ui.notify(
            `system2-init: ${rel} differs from the package payload; left unchanged (pass --force to overwrite).`,
            "info",
          );
          continue;
        }
        if (current !== null && force) {
          // PRINT exactly which user-modified managed file is being replaced BEFORE
          // overwriting it.
          ctx.ui.notify(`system2-init: --force replacing user-modified ${rel}`, "info");
          replaced.push(rel);
        }
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.writeFileSync(target, payloadBytes);
        written.push(rel);
      }

      if (rejected.length > 0) {
        ctx.ui.notify(
          `system2-init: refused out-of-root or missing managed paths (nothing written for these): ${rejected.join(", ")}`,
          "error",
        );
      }
      ctx.ui.notify(
        `system2-init: wrote ${written.length}, skipped ${skipped.length}, replaced ${replaced.length}.`,
        "info",
      );
    },
  });
}
