// Generated by the System2 compiler. Do not edit by hand.
// /system2-init copies managed payload files into the current project.
// Targets must stay within the project root; user changes require --force.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import * as fs from "node:fs";
import * as path from "node:path";
import * as process from "node:process";
import { Buffer } from "node:buffer";
import { fileURLToPath } from "node:url";

// Project-relative files copied from payload/project/.
const MANAGED_FILES: string[] = [".pi/SYSTEM.md", "AGENTS.md", "system2.pi.lock.json"];

// Resolve the payload relative to this installed module.
const HERE = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(HERE, "..");
const PAYLOAD_ROOT = path.join(PACKAGE_ROOT, "payload", "project");

// Return null when a managed path escapes the project root.
function resolveWithinRoot(projectRoot: string, rel: string): string | null {
  if (path.isAbsolute(rel)) return null;
  const target = path.resolve(projectRoot, rel);
  const prefix = projectRoot.endsWith(path.sep) ? projectRoot : projectRoot + path.sep;
  if (target !== projectRoot && !target.startsWith(prefix)) return null;
  return target;
}

function readIfExists(p: string): Buffer | null {
  try {
    return fs.readFileSync(p);
  } catch {
    return null;
  }
}

export default function (pi: ExtensionAPI) {
  pi.registerCommand("/system2-init", {
    description:
      "Materialize System2 project files (AGENTS.md, .pi/SYSTEM.md, the lock) into this project from the package payload. Pass --force to overwrite user-modified files.",
    handler: async (args, ctx) => {
      const force = args.trim() === "--force";
      const projectRoot = process.cwd();
      const written: string[] = [];
      const skipped: string[] = [];
      const replaced: string[] = [];
      const rejected: string[] = [];

      for (const rel of MANAGED_FILES) {
        const target = resolveWithinRoot(projectRoot, rel);
        if (target === null) {
          // Refuse paths outside the project root.
          rejected.push(rel);
          continue;
        }
        const payloadBytes = readIfExists(path.join(PAYLOAD_ROOT, rel));
        if (payloadBytes === null) {
          rejected.push(rel);
          continue;
        }
        const current = readIfExists(target);
        if (current !== null && current.equals(payloadBytes)) {
          // idempotent: already identical -> skip (second run is a zero-diff no-op).
          skipped.push(rel);
          continue;
        }
        if (current !== null && !force) {
          // user-modified (differs from payload) and no --force -> leave untouched.
          skipped.push(rel);
          ctx.ui.notify(
            `system2-init: ${rel} differs from the package payload; left unchanged (pass --force to overwrite).`,
            "info",
          );
          continue;
        }
        if (current !== null && force) {
          // PRINT exactly which user-modified managed file is being replaced BEFORE
          // overwriting it.
          ctx.ui.notify(`system2-init: --force replacing user-modified ${rel}`, "info");
          replaced.push(rel);
        }
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.writeFileSync(target, payloadBytes);
        written.push(rel);
      }

      if (rejected.length > 0) {
        ctx.ui.notify(
          `system2-init: refused out-of-root or missing managed paths (nothing written for these): ${rejected.join(", ")}`,
          "error",
        );
      }
      ctx.ui.notify(
        `system2-init: wrote ${written.length}, skipped ${skipped.length}, replaced ${replaced.length}.`,
        "info",
      );
    },
  });
}
