// Generated by the System2 compiler. Do not edit by hand.
// The tool_call handler blocks unsafe operations before execution.

import type { ExtensionAPI, ToolCallEvent, BashToolCallEvent } from "@earendil-works/pi-coding-agent";

// Dangerous-command matchers; order is semantic.
const DANGEROUS_REGEXES: [RegExp, string][] = [
  [new RegExp("\\brm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*|-r\\s+-f|-f\\s+-r|-[a-zA-Z]*r[a-zA-Z]*\\s+-[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*\\s+-[a-zA-Z]*r[a-zA-Z]*|--recursive\\s+--force|--force\\s+--recursive|--recursive\\s+-f|-f\\s+--recursive|-r\\s+--force|--force\\s+-r|--recursive[^|;&]*-f|-f[^|;&]*--recursive|-r[^|;&]*--force|--force[^|;&]*-r)\\s*(/|/\\*)\\s*($|;|\\||&)", "m"), "rm -rf targeting root filesystem (/) is extremely dangerous"],
  [new RegExp("\\brm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*|-r\\s+-f|-f\\s+-r|-[a-zA-Z]*r[a-zA-Z]*\\s+-[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*\\s+-[a-zA-Z]*r[a-zA-Z]*|--recursive\\s+--force|--force\\s+--recursive|--recursive\\s+-f|-f\\s+--recursive|-r\\s+--force|--force\\s+-r|--recursive[^|;&]*-f|-f[^|;&]*--recursive|-r[^|;&]*--force|--force[^|;&]*-r)\\s*\\./?(?:\\s|$|;|\\||&)", "m"), "rm -rf targeting current directory (.) could delete critical files"],
  [new RegExp("\\brm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*|-r\\s+-f|-f\\s+-r|-[a-zA-Z]*r[a-zA-Z]*\\s+-[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*\\s+-[a-zA-Z]*r[a-zA-Z]*|--recursive\\s+--force|--force\\s+--recursive|--recursive\\s+-f|-f\\s+--recursive|-r\\s+--force|--force\\s+-r|--recursive[^|;&]*-f|-f[^|;&]*--recursive|-r[^|;&]*--force|--force[^|;&]*-r)\\s*\\.\\./?(?:\\s|$|;|\\||&)", "m"), "rm -rf targeting parent directory (..) could delete critical files"],
  [new RegExp("\\brm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*)\\s*~", "m"), "rm -rf targeting the home directory (~) could delete user data"],
  [new RegExp("\\bsudo\\s+rm\\s+(-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*r[a-zA-Z]*|-r\\s+-f|-f\\s+-r|-[a-zA-Z]*r[a-zA-Z]*\\s+-[a-zA-Z]*f[a-zA-Z]*|-[a-zA-Z]*f[a-zA-Z]*\\s+-[a-zA-Z]*r[a-zA-Z]*|--recursive\\s+--force|--force\\s+--recursive|--recursive\\s+-f|-f\\s+--recursive|-r\\s+--force|--force\\s+-r|--recursive[^|;&]*-f|-f[^|;&]*--recursive|-r[^|;&]*--force|--force[^|;&]*-r)\\s+", "m"), "sudo rm -rf with elevated privileges is extremely dangerous"],
  [new RegExp("\\bchmod\\s+(.*\\s+)?777\\s+", "m"), "chmod 777 makes files world-writable and executable, a security risk"],
  [new RegExp("\\bgit\\s+reset\\s+--hard\\b", "m"), "git reset --hard discards uncommitted changes permanently"],
  [new RegExp("\\bgit\\s+push\\s+[^;|&]*--force(-with-lease)?[^;|&]*\\b(main|master)\\b", "m"), "git push --force to main/master can destroy shared commit history"],
  [new RegExp("\\bgit\\s+push\\s+[^;|&]*\\b(main|master)\\b[^;|&]*--force(-with-lease)?", "m"), "git push --force to main/master can destroy shared commit history"],
  [new RegExp("\\bgit\\s+push\\s+[^;|&]*-f\\s+[^;|&]*\\b(main|master)\\b", "m"), "git push -f to main/master can destroy shared commit history"],
  [new RegExp("\\bgit\\s+push\\s+[^;|&]*\\b(main|master)\\b[^;|&]*\\s+-f\\b", "m"), "git push -f to main/master can destroy shared commit history"],
  [new RegExp("\\bmkfs\\b", "m"), "mkfs reformats a filesystem and destroys all data on the device"],
  [new RegExp("\\bdd\\s+[^|;&]*\\bof=", "m"), "dd writing to a device/file (of=) can irreversibly overwrite data"],
  [new RegExp("\\bshutdown\\b", "m"), "shutdown halts the machine"],
  [new RegExp("\\b(curl|wget)\\b[^|]*\\|\\s*(sudo\\s+)?(sh|bash|zsh)\\b", "m"), "piping a downloaded script straight into a shell executes untrusted code"],
  [new RegExp("\\bDROP\\s+TABLE\\b", "i"), "DROP TABLE would permanently delete a database table and its data"],
  [new RegExp("\\bDELETE\\s+FROM\\s+\\w+\\s*($|;|\\|)", "im"), "DELETE FROM without a WHERE clause would delete all rows in the table"],
];

// Ported from sensitive-file-protector.py: segment/basename-anchored.
const SENSITIVE_REGEXES: [RegExp, string][] = [
  [new RegExp("(^|/)\\.env$", ""), "Environment file (.env)"],
  [new RegExp("(^|/)\\.env\\.[A-Za-z0-9_-]+$", ""), "Environment file (.env.*)"],
  [new RegExp("(^|/)\\.ssh(/|$)", ""), "SSH directory (.ssh/)"],
  [new RegExp("(^|/)\\.git(/|$)", ""), "Git directory (.git/)"],
  [new RegExp("(^|/)\\.aws(/|$)", ""), "AWS credentials directory (.aws/)"],
  [new RegExp("(^|/)\\.gnupg(/|$)", ""), "GPG directory (.gnupg/)"],
  [new RegExp("credentials", "i"), "File containing 'credentials'"],
  [new RegExp("secrets", "i"), "File containing 'secrets'"],
  [new RegExp("\\.pem$", "i"), "PEM certificate/key file (*.pem)"],
  [new RegExp("\\.key$", "i"), "Key file (*.key)"],
  [new RegExp("(^|/)id_rsa$", ""), "RSA private key (id_rsa)"],
  [new RegExp("(^|/)id_ed25519$", ""), "Ed25519 private key (id_ed25519)"],
  [new RegExp("(^|/)id_ecdsa$", ""), "ECDSA private key (id_ecdsa)"],
  [new RegExp("(^|/)\\.netrc$", ""), "Netrc credentials file (.netrc)"],
  [new RegExp("(^|/)\\.npmrc$", ""), "NPM config file (.npmrc) - may contain tokens"],
  [new RegExp("(^|/)\\.pypirc$", ""), "PyPI config file (.pypirc) - may contain tokens"],
];

// Per-role write scopes; absent or empty scopes deny writes.
const ROLE_WRITE_SCOPES: Map<string, string> = new Map([
  ["repo-governor", "^(CLAUDE\\.md|AGENTS\\.md|\\.claude/settings\\.json|spec/INDEX\\.md)$"],
  ["spec-coordinator", "^spec/context\\.md$"],
  ["requirements-engineer", "^spec/requirements\\.md$"],
  ["design-architect", "(?:^spec/design\\.md$)|(?:^spec/interfaces\\.json$)|(?:^spec/module-boundaries\\.json$)"],
  ["task-planner", "^spec/tasks\\.md$"],
  ["executor", "^(?!third_party/|vendor/|node_modules/|dist/|build/|out/|\\.git/).*(^spec/.*\\.md$|^docs/.*\\.md$|^README\\.md$|^CHANGELOG\\.md$|(^|/)(BUILD|WORKSPACE)(\\.bazel)?$|.*\\.(py|go|java|kt|kts|ts|tsx|js|jsx|rs|c|cc|cpp|h|hpp|cs|proto|sql|yaml|yml|json|toml|sh|bazel|bzl)$)"],
  ["test-engineer", "^(?!third_party/|vendor/|node_modules/|dist/|build/|out/|\\.git/).*(^spec/.*\\.md$|^docs/.*\\.md$|.*(/__tests__/|/tests?/).*\\.(py|go|java|kt|kts|ts|tsx|js|jsx|rs|c|cc|cpp|cs)$|.*(_test\\.go|\\.test\\.(ts|tsx|js|jsx)|\\.spec\\.(ts|tsx|js|jsx)|test_.*\\.py|.*_test\\.py)$|(^|/)(BUILD|WORKSPACE)(\\.bazel)?$|.*\\.(yaml|yml|json|toml)$)"],
  ["security-sentinel", "^spec/security\\.md$"],
  ["eval-engineer", "^(spec/evals\\.md|evals/.*\\.(md|py|yaml|yml|json|toml))$"],
  ["docs-release", "^(README\\.md|CHANGELOG\\.md|MIGRATIONS\\.md|docs/.*\\.md|spec/.*\\.md)$"],
  ["code-reviewer", ""],
  ["postmortem-scribe", "^postmortems/.*\\.md$"],
  ["mcp-toolsmith", "^(spec/mcp\\.md|mcp/.*\\.(md|py|ts|js|json|yaml|yml))$"],
]);

// Roles permitted to write when their path also matches the scope.
const WRITEABLE_ROLES: Set<string> = new Set(["code-reviewer", "design-architect", "docs-release", "eval-engineer", "executor", "mcp-toolsmith", "postmortem-scribe", "repo-governor", "requirements-engineer", "security-sentinel", "spec-coordinator", "task-planner", "test-engineer"]);

const VALID_ROLES: string[] = ["repo-governor", "spec-coordinator", "requirements-engineer", "design-architect", "task-planner", "executor", "test-engineer", "security-sentinel", "eval-engineer", "docs-release", "code-reviewer", "postmortem-scribe", "mcp-toolsmith"];
let activeRole: string = "executor";

// Extract every supported path alias before applying policy.
const PATH_KEYS: string[] = [
  "path", "file_path", "filepath", "filename", "file", "target_file",
  "from", "to", "source", "destination", "old_path", "new_path",
];

function pathsOf(event: ToolCallEvent): string[] {
  const input = (event.input ?? {}) as Record<string, unknown>;
  const out: string[] = [];
  for (const key of PATH_KEYS) {
    const v = input[key];
    if (typeof v === "string" && v.length > 0) out.push(v);
  }
  return out;
}

function dangerousReason(command: string): string | undefined {
  for (const [re, reason] of DANGEROUS_REGEXES) {
    if (re.test(command)) return `block-dangerous: ${reason}`;
  }
  return undefined;
}

function sensitiveHit(text: string | undefined): string | undefined {
  if (!text) return undefined;
  for (const [re, description] of SENSITIVE_REGEXES) {
    if (re.test(text)) return description;
  }
  return undefined;
}

// Normalize project-relative paths and return null on any escape.
function normalizeProjectPath(p: string): string | null {
  if (typeof p !== "string" || p.length === 0) return null;
  if (p === "~" || p.startsWith("~/")) return null; // home dir: outside project
  const slashed = p.replace(/\\/g, "/");
  if (slashed.startsWith("/")) return null; // absolute: cannot confirm in-project -> block
  const segs: string[] = [];
  for (const part of slashed.split("/")) {
    if (part === "" || part === ".") continue;
    if (part === "..") {
      if (segs.length === 0) return null; // escapes the project root -> block
      segs.pop();
      continue;
    }
    segs.push(part);
  }
  return segs.join("/");
}

function offLeasePath(event: ToolCallEvent): string | undefined {
  if (event.toolName !== "write" && event.toolName !== "edit") return undefined;
  const paths = pathsOf(event);
  if (paths.length === 0) return undefined;
  // Unscoped roles cannot write.
  const scope = ROLE_WRITE_SCOPES.get(activeRole);
  if (!WRITEABLE_ROLES.has(activeRole) || !scope) return paths[0];
  let re: RegExp;
  try {
    re = new RegExp("^(?:" + scope + ")");
  } catch {
    return paths[0]; // an uncompilable scope fails closed, not open
  }
  for (const p of paths) {
    const norm = normalizeProjectPath(p);
    if (norm === null || !re.test(norm)) return p; // escape or off-scope -> block
  }
  return undefined;
}

export default function (pi: ExtensionAPI) {
  // Block unsafe tool calls before execution.
  pi.on("tool_call", (event) => {
    // block-dangerous: a bash command matching the ported regex set -> hard block.
    if (event.toolName === "bash") {
      const command = (event as BashToolCallEvent).input.command;
      const reason = dangerousReason(command);
      if (reason) return { block: true, reason };
      const sBash = sensitiveHit(command);
      if (sBash) {
        return { block: true, reason: `protect-sensitive: ${sBash}` };
      }
      return;
    }
    // protect-sensitive: any path-bearing input touching a sensitive path -> hard block.
    for (const p of pathsOf(event)) {
      const sPath = sensitiveHit(p);
      if (sPath) {
        return { block: true, reason: `protect-sensitive: ${sPath}` };
      }
    }
    // enforce-lease: a write/edit outside the active role's write scope -> hard block.
    const off = offLeasePath(event);
    if (off) {
      return { block: true, reason: `enforce-lease: ${off} is outside the write scope for role ${activeRole}` };
    }
    return; // allow
  });

  // Report the budget after the agent ends; this does not block.
  pi.on("agent_end", (_event, ctx) => {
    ctx.ui.notify(
      "System2 budget: report files touched and lines added/removed in your completion summary.",
      "info",
    );
  });

  // Inject the orchestrator context before the agent starts.
  pi.on("before_agent_start", (event) => ({
    systemPrompt: `${event.systemPrompt}\n\nSystem2 orchestrator context is in .pi/SYSTEM.md. Drive the gate graph 0 -> 5 and delegate via /delegate <role>.`,
  }));

  // Limit /delegate to known roles.
  pi.registerCommand("/delegate", {
    description: "Delegate a sub-task to one of the 13 System2 roles.",
    handler: async (args, ctx) => {
      const role = args.trim();
      if (!VALID_ROLES.includes(role)) {
        ctx.ui.notify(
          `Unknown role ${JSON.stringify(role)}. Valid roles: ${VALID_ROLES.join(", ")}.`,
          "error",
        );
        return;
      }
      activeRole = role; // role-switch: the lease gate now enforces this role's scope
      ctx.ui.notify(`Delegated to ${role}. Load .pi/prompts/role-${role}.md.`, "info");
    },
  });
}
