#!/usr/bin/env bash
# Generated by the System2 compiler (Goose backend). Thin launcher only:
# validate -> build an ephemeral XDG_CONFIG_HOME -> goose run. No workflow
# logic, no translation, no policy lives here (C6/NFR-007). It NEVER writes
# to ~/.config/goose.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NO_PERMISSIONS="${SYSTEM2_NO_PERMISSIONS:-0}"
KEEP_CONFIG="${SYSTEM2_KEEP_CONFIG:-0}"
USER_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/goose"
USER_CONFIG="$USER_CONFIG_DIR/config.yaml"
LOCAL_PERMISSION="$HERE/goose/permission.yaml"

# 1. Validate the orchestrator and every role sub-recipe (fail fast).
goose recipe validate "$HERE/system2.recipe.yaml"
for recipe in "$HERE/agents/"*.recipe.yaml; do
  [ -e "$recipe" ] || continue  # guard against an empty glob
  goose recipe validate "$recipe"
done

export GOOSE_MODE=smart_approve

# 2. Permission delivery.
if [ "$NO_PERMISSIONS" = "1" ]; then
  echo "NOTICE: SYSTEM2_NO_PERMISSIONS=1 — running against YOUR OWN goose" >&2
  echo "NOTICE: config (~/.config/goose). The System2-adapted permission" >&2
  echo "NOTICE: policy is NOT applied; block-dangerous/protect-sensitive are" >&2
  echo "NOTICE: NOT active this run. See system2.goose.lock.json." >&2
  goose run --recipe "$HERE/system2.recipe.yaml" --params task="${1:-}"
  exit $?
fi

# DEFAULT: build a throwaway XDG_CONFIG_HOME so the adapted policy governs
# THIS run without ever touching ~/.config/goose. The ephemeral dir may hold
# the user's provider keys (copied config.yaml), so it is created owner-only
# (umask 077 -> dir 700, files 600) and removed on exit OR signal.
umask 077
EPHEMERAL_CONFIG="$(mktemp -d "${TMPDIR:-/tmp}/system2-goose-config.XXXXXX")"
chmod 700 "$EPHEMERAL_CONFIG"
cleanup() {
  if [ "$KEEP_CONFIG" = "1" ]; then
    echo "NOTICE: SYSTEM2_KEEP_CONFIG=1 — kept ephemeral config at $EPHEMERAL_CONFIG" >&2
  else
    rm -rf "$EPHEMERAL_CONFIG"
  fi
}
# Cover normal exit AND catchable signals (Ctrl-C / kill / hangup) so the
# secret copy is not left in TMPDIR. SIGKILL is uncatchable by design.
trap cleanup EXIT INT TERM HUP

mkdir -p "$EPHEMERAL_CONFIG/goose"
chmod 700 "$EPHEMERAL_CONFIG/goose"
if [ -f "$USER_CONFIG" ]; then
  cp "$USER_CONFIG" "$EPHEMERAL_CONFIG/goose/config.yaml"
  chmod 600 "$EPHEMERAL_CONFIG/goose/config.yaml"
  echo "Carried your goose config.yaml (provider/model/keys) into the ephemeral config." >&2
else
  echo "NOTICE: no ~/.config/goose/config.yaml found; the ephemeral config has" >&2
  echo "NOTICE: only the System2 permission policy (set provider/model in env)." >&2
fi
cp "$LOCAL_PERMISSION" "$EPHEMERAL_CONFIG/goose/permission.yaml"
chmod 600 "$EPHEMERAL_CONFIG/goose/permission.yaml"

echo "MODE: ADAPTED permission policy active via an EPHEMERAL XDG_CONFIG_HOME." >&2
echo "MODE: This is enforcement-APPROXIMATE (smart_approve + permission.yaml)," >&2
echo "MODE: NOT native blocking. ~/.config/goose is NEVER modified. See" >&2
echo "MODE: system2.goose.lock.json for the full degradation report." >&2

# 3. Run the workflow under smart_approve (a gate exists; never auto),
#    reading config + permission policy from the ephemeral dir only.
XDG_CONFIG_HOME="$EPHEMERAL_CONFIG" goose run \
  --recipe "$HERE/system2.recipe.yaml" --params task="${1:-}"
